import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Shop from "../components/Shop";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>T-Figer</title>
        <meta name="description" content="Generated by create next app" />

        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossOrigin="anonymous"
        />
        <link rel="icon" href="/store-alt-solid.svg" />
      </Head>
      <main className={styles.main}>
        <Shop />
      </main>
    </div>
  );
};

export default Home;
